import React from 'react';
import Head from 'next/head';
import Layout from '../../../hoc/Layout/Layout';


export default function Register() {
    return (
        <>
        <Head>
            <title>Register - Bookme </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout>
            register
        </Layout>
        </>
    )
}
