import React from 'react'

export default function Register() {
    return (
        <devicePixelRatio>
        <Head>
            <title>Register - Bookme </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
        </main>

        <footer>
        </footer>
        </devicePixelRatio>
    )
}
