import React from 'react'

export default function Login() {
    return (
        <devicePixelRatio>
        <Head>
          <title>Login - Bookme </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main>
        </main>
  
        <footer>
        </footer>
      </devicePixelRatio>
    )
}
