import React from 'react';
import Head from 'next/head';
import Layout from '../../../hoc/Layout/Layout';
import LoginUI from '../../../components/Auth/Login/Login';

export default function Login() {
    return (
        <>
        <Head>
          <title>Login - Bookme </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
        </Head>
        <Layout>
            <LoginUI />
        </Layout>
      </>
    )
}
