import React from 'react';
import Head from 'next/head';
import Layout from '../../../hoc/Layout/Layout';

export default function Login() {
    return (
        <>
        <Head>
          <title>Login - Bookme </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
           login
        </Layout>
      </>
    )
}
