import React from 'react';
import Head from 'next/head'
import Layout from '../hoc/Layout/Layout';
import HomeUI from '../components/Home/Home';
import NavTab from '../components/NavTabs/NavTab';


export default function Home(props) {
  console.log(props.getAllData)

  return (
    <div>
      <Head>
        <title>Bookme </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet" />
      </Head>
     
      <Layout>
          <NavTab />
          <HomeUI />
      </Layout>
    </div>
  )
}
